CREATE TABLE "users" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(
		START WITH 1
		INCREMENT BY 1
	) PRIMARY KEY,
  "name" varchar,
  "role" varchar,
  "email" varchar,
  "password_hash" varchar
);

CREATE TABLE "refresh_tokens"(
  "user_id" INT NOT NULL,
  "token" text NOT NULL
);


ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
